#!/bin/bash

APP=$0
APP=${APP##*/}

usage()
{
    echo "usage: ${APP} <install|clean>"
    echo
    echo "install   -   install the package"
    echo "clean     -   clean the installation"
}

ROOT='/etc/math_service/'

install()
{
    if [ -d $ROOT ]; then
        mv $ROOT $ROOT'.bak'
        rm -rf $ROOT
    fi
    mkdir -p $ROOT
    cp -r math_service.py v1/ $ROOT
}

clean()
{
    rm -rf $ROOT
}

if [ $# -lt 1 ]; then
    usage
    exit 1
fi

case "$1" in
    clean)
        clean
        ;;
    install)
        install
        ;;
    *)
        usage
        exit 1
esac
exit 0
